### ISSUE TITLE
Miniscope-LFOV issues（R23，R24）

### ISSUE THREAD

**Issue by 931436690** [Aharoni-Lab/Miniscope-LFOV#1]
Hi，there.

We are using your open source materials to build our own Miniscope-LFOV. Thanks for sharing, they are very good profiles.But Miniscope-LFOV's open source materials seem to have some problems, and the shared gerber is inconsistent with the board schematic (the gerber file does not have R23 and R24 resistors, and its pull-up cable; Schematics and PCB files have R23, R24, and their pull-up cables).

At present, we have finished processing the circuit board using the shared gerber file, and have not yet soldered the chip (the material is very difficult to buy), we have a few questions that need to be consulted:

Question 1: Are R23 and R24 necessarily needed? Can I use a board without R23, R24?

I think that by connecting the GPIO0 and TP3 endpoints of the DAQ circuit board, GPIO1 and TP4 endpoints, the firmware program is modified as follows; it is possible to achieve a setting of two LEDs that are always on; But I'm not 100% sure, do you have any suggestion?

 

#define LTC3218_ENT1                       17 //definitions.h; adding code like this.

#define LTC3218_ENT2              18 // definitions.h; adding code like this.

 

/////////////////////uvc.c; adding code like this in CyFxUVCApplnInit (void).

apiRetStatus = CyU3PDeviceGpioOverride (LTC3218_ENT1, CyTrue);

if (apiRetStatus != 0)

{

           //CyU3PDebugPrint (4, "GPIO Override failed, Error Code = %d\n", apiRetStatus);

           CyFxAppErrorHandler (apiRetStatus);

}

 

/* nReset of the Python Trough the FPDLink  */

gpioConfig.outValue    = CyFalse;

gpioConfig.driveLowEn  = CyTrue;

gpioConfig.driveHighEn = CyTrue;

gpioConfig.inputEn     = CyFalse;

gpioConfig.intrMode    = CY_U3P_GPIO_NO_INTR;

apiRetStatus           = CyU3PGpioSetSimpleConfig (LTC3218_ENT1, &gpioConfig);

apiRetStatus = CyU3PDeviceGpioOverride (LTC3218_ENT2, CyTrue);

if (apiRetStatus != 0)

{

           //CyU3PDebugPrint (4, "GPIO Override failed, Error Code = %d\n", apiRetStatus);

           CyFxAppErrorHandler (apiRetStatus);

}

 

/* nReset of the Python Trough the FPDLink  */

gpioConfig.outValue    = CyFalse;

gpioConfig.driveLowEn  = CyTrue;

gpioConfig.driveHighEn = CyTrue;

gpioConfig.inputEn     = CyFalse;

gpioConfig.intrMode    = CY_U3P_GPIO_NO_INTR;

apiRetStatus           = CyU3PGpioSetSimpleConfig (LTC3218_ENT2, &gpioConfig);

/////////////////////uvc.c; adding code like this in CyFxUvcApplnDmaCallback (….).

status = CyU3PGpioSetValue(LTC3218_ENT1, CyTrue);

status = CyU3PGpioSetValue(LTC3218_ENT2, CyTrue);

 

 

Question 2: Do we need to generate the gerber file ourselves according to the existing 'Kicad_LFOV_RigidFlex_Assembly.kicad_pcb' file? Then rework the board once (although it will cost some costs), but we need to confirm that the board has no other problems.

However, the pull-up resistance (R23, R24) of 0 ohms can only ensure that the LED is always on, and cannot achieve switch control; If the two LEDs are lit in turn in the later stage, will they be replaced with resistors of other values (such as 1K resistors); What experience do you have in pull-up resistors?

I left the same message on github and email, sorry for this; the processing plant is waiting for us to reply to the message, which is a little urgent for the current problem.

Best Wishes!

**Comment by 931436690** [comment]
We can see the differences between the gerber file and PCB file.
![sch](https://user-images.githubusercontent.com/64941378/180756385-95d3dbee-a334-472a-9e7e-5a8289f87d4a.JPG)
![gerber file](https://user-images.githubusercontent.com/64941378/180756572-347b7a78-6d19-4e45-a746-cad2eb9c01ca.png)
![PCB file](https://user-images.githubusercontent.com/64941378/180756578-346b8e0d-0329-463d-b92c-0e329dfb97fa.png)

**Comment by daharoni** [comment]
Hi! It sounds like you have a great understanding of the system already. Those two (R23 and R24) resistors were added in a later design to allow someone to just always have the LEDs enabled without dealing with the GPO of the serializer/deserializer. These resistors are not necessary so there should be no need to regenerate the Gerbers. If you do want to directly enable the LEDs without the use of the GPO pins, you can always just cut the ENT1, 2 traces and solder a small bodge wire to 3.3V on the PCB.

The easiest thing, if you don't mind always having the LED enabled, is on the DAQ PCB just connect the GPIO 4 pin header directly to 3.3V. This will pull the serializer's GPO pins high without needing to mess around with any of the DAQ firmware. I hope this helps!

**Comment by 931436690** [comment]
It's a good idea(connectting  the GPIO 4 pin header directly to 3.3V).
Thank you very much.
Best wishes.
