### ISSUE TITLE
Miniscope-LFOV  Configuration(Json file of QT software)

### ISSUE THREAD

**Issue by 931436690** [Aharoni-Lab/Miniscope-LFOV#2]
Hi, there.
  With the help of your open source materials, we fabricated our own board; thanks a lot. I have several questions about software configuration:
1. For the DAQ firmware, should I "#define SIMINISCOPE_2592_1944" and regenerate the firmware? The Json configuration of the QT software should be able to change the current camera‘s configuration (change to a camera with a resolution of 2592*1944 pixels).
2. For QT software, is there a Json configuration file for LFOV? Or do we need to write a configuration file by ourselves based on Miniscope_V4_BNO and Siminiscope_1024X768?
  Best wishes.

**Comment by daharoni** [comment]
Hey, Sorry I missed this post until now.

The DAQ firmware needs to have an entry for all possible resolutions you might want to use. You can just follow how other resolutions are defined in the descriptor and uvc.c files and add new ones after the ones already there. Then you will want to make a new entry in the deviceConfig.json file for the new resolution you want to use. Finally, you will use that new "deviceType" in the userConfig.json file that gets loaded up by the Miniscope DAQ software.

**Comment by 931436690** [comment]
Sorry for not clarifying the problem.Currently we don't want to change the imaging size of the LFOV (the imaging size in your paper should be enough ; your paper:Miniscope-LFOV: A large field of view, single cell resolution, miniature microscope for wired and wire-free imaging of neural dynamics in freely behaving animals), we just want it to work. 

I connected the LFOV to the DAQ board and can't see any images. I think there should be a Json configuration file（using for QT software) to set the relevant I2C address and CMOS related parameters. Can you share it with us?  In addition to the Json file of the QT software, do we need other configuration in order to make LFOV see the image?

**Comment by daharoni** [comment]
Oh ok. I think I understand.

In the most recent release, the Miniscope DAQ software natively supports one configuration of the MiniLFOV. All you should need to do to get started is:

1. Open one of the example user files.
2. Replace the "deviceType:" entry under "My V4 Miniscope" from "Miniscope_V4_BNO" to "Siminiscope_1024X768"
3. Run the DAQ software and use this updated user config file. 

We have a bunch of other configurations for the MiniLFOV too but I can't seem to track down the videoDevices.json file which has these additional configurations. I should be able to find it soon and I'll update everything on this repo.

**Comment by 931436690** [comment]
We are very much looking forward to seeing these Json files. Please let us know when you find them. 
Thank you very much. Your open source materials are very helpful to us.

**Comment by daharoni** [comment]
Hi @931436690,
Can you try grabbing the" videoDevices.json" file from here, https://drive.google.com/file/d/1TcGFhXwIQlBfkbzA89tM9PcrPqrXLsfU/view?usp=sharing (GitHub doesn't support posting JSON files directly in this response). And then replace the "deviceConfigs/videoDevices.json" file your Miniscope DAQ Software directory? This should give you support for many MiniLFOV configurations which you would select from by changing the "deviceType:" in your user configuration file.

Below shows the different MiniLFOV devices types that should now be enabled:
![image](https://user-images.githubusercontent.com/16613835/195934281-61419b76-8aa4-4177-b2b5-a41cbb3c95aa.png)

**Comment by 931436690** [comment]
Thanks a lot for your answer! We will test the board.
 Simple power-on test today, it seems that the CMOS and LED adjustment is normal. But when the LED control is turned to 0 (QT software), the blue LED is blinking; I remember seeing the answer to this question (it seems that the potentiometer's resistance value is not large enough), but I forget where this problem appeared.
